# Generated by Django 5.1.5 on 2025-02-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_image',
            field=models.TextField(default='https://imgs.search.brave.com/XGdJ4-IfhuybNdfZgNJK7LWugrtpad9RemRulqyzjfI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzA5LzYzLzk3LzY3/LzM2MF9GXzk2Mzk3/NjcwNV9JV2ZEQWNY/M3VxNVJFUmVSYnhi/WU5aNXpxeTdjMVA3/Ni5qcGc'),
        ),
    ]
