# Generated by Django 5.1.5 on 2025-02-09 11:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blogpost_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image_url',
            field=models.TextField(default=api.models.default_imageurl),
        ),
    ]
