# Generated by Django 5.1.5 on 2025-02-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_blogpost_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image_url',
            field=models.URLField(),
        ),
    ]
