# Generated by Django 5.1.5 on 2025-02-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_blogpost_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
