# Generated by Django 5.1.5 on 2025-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
