# Generated by Django 5.1.5 on 2025-02-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_share_shares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='shares',
            new_name='share_counts',
        ),
    ]
