# Generated by Django 5.1.5 on 2025-02-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_comment_user_alter_like_user_alter_share_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='share_counts',
            new_name='shares',
        ),
    ]
